spring:
  application:
    name: service-registry

 
server:
  port: 8761
  
  
  eureka:
    client:
      serviceUrl:
        defaultZone: http://servicereg:8761/eureka/
      register-with-eureka: true
      fetch-registry: true
