version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: pravin
      POSTGRES_PASSWORD: pravin
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    networks:
      - my-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pravin.chavan2729@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pravin
    ports:
      - "5050:80"
    networks:
      - my-network
    depends_on:
      - postgres

networks:
  my-network:

volumes:
  postgres-data:
