spring:
  application:
    name: address

  server:
    port: 8082

  datasource:
    url: jdbc:postgresql://localhost:5432/pravin
    username: pravin
    password: pravin

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
