spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pravin1129/Spring-Boot-.git
          default-label: master  # ✅ Make sure there are no TAB characters here
          clone-on-start: true

server:
  port: 8083

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
